<?php
/**
 * Custom functions
 */
 
 //Automatically add Bootstrap responsive image class to images uploaded in the WP Editor
 
add_filter( 'image_send_to_editor', 'responsive_images', 10, 7);
   function responsive_images($html, $id, $alt, $title, $align, $url, $size ) {
	   $url = wp_get_attachment_url($id); // Grab the current image URL
	   $html = '<a href="' . $url .  '" class="" rel="your-rel"><img class="img-responsive" src="'.$url.'" /></a>';
	   return $html;
   }


/**
 * Get the users Github Repo Listing
 */
function i4web_get_repos_test() {
    $transient_key = 'sern_repos';
    $repos = get_transient( $transient_key );
    if ( false !== $repos )
        return $repos;

    $response = wp_remote_get( 'https://api.github.com/users/serneum/repos?sort=created_at' );
    if ( is_wp_error( $response ) )
        return array();

    $repos = json_decode( wp_remote_retrieve_body( $response ) );
    if ( ! is_array( $repos ) )
        return array();

    set_transient( $transient_key, $repos, 1 );
	
    return (array) $repos;
}

/**
 * Get the users Github information
 */
function i4web_get_git_avatar() {
    $transient_key = 'sern_avatar';
    $repos = get_transient( $transient_key );
    if ( false !== $repos )
        return $repos;

    $response = wp_remote_get( 'https://api.github.com/users/serneum' );
	
    if ( is_wp_error( $response ) )
        return array();
		
    $repos = json_decode( wp_remote_retrieve_body( $response ) );
	
	
    
	// 60 seconds * 60 minutes
	$hourInSeconds = 3600;
	
	//Transients are set in seconds. Changing the time here will change when the transient expires. default set to 24 hours
    set_transient( $transient_key, $repos, 24 * $hourInSeconds );
	
    return (array) $repos;
}


/**
 * Alter the default excerpt length 
 */
function custom_excerpt_length( $length ) {
	return 15;
}
add_filter( 'excerpt_length', 'custom_excerpt_length', 999 );


function continue_reading_link() {
	return '';
}

function auto_excerpt_more( $more ) {
	return ' &hellip;' . continue_reading_link();
}
add_filter( 'excerpt_more', 'auto_excerpt_more' );


/**
 * Remove the <p> that are autogenerated around the output of the term_description function 
 */
remove_filter('term_description','wpautop');


/**
 * Add <kbd> shortcode for use in the visual editor
 */
function kbdtag_func( $atts, $content="" ) {
     return "<kbd>$content</kbd>";
}

//Register the shortcode [kbd]
add_shortcode( 'kbd','kbdtag_func' ) ;

/**
 * Add <pre> shortcode for use in the visual editor
 */
function pretag_func( $atts, $content="" ) {
     return "<pre>$content</pre>";
}

//Register the shortcode [kbd]
add_shortcode( 'pre','pretag_func' ) ;



?>